<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
-- MySQL Script generated by MySQL Workbench
-- Sun Mar  7 20:46:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OPTICA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `OPTICA` ;

-- -----------------------------------------------------
-- Schema OPTICA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OPTICA` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `OPTICA` ;

-- -----------------------------------------------------
-- Table `Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Clients` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Clients` (
  `id_clientes` VARCHAR(32) NULL,
  `Nom_client` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `adreça` VARCHAR(45) NULL,
  `codi postal` VARCHAR(5) NULL,
  `e_mail` VARCHAR(45) NULL,
  `data_registre` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `recomanat_per` VARCHAR(45) NULL,
  `Ventes_id_venta` VARCHAR(16) NOT NULL,
  `Ulleres_id_ulleres` INT NOT NULL,
  PRIMARY KEY (`id_clientes`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Nom_client_UNIQUE` ON `Clients` (`Nom_client` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Empleats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empleats` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Empleats` (
  `id_empleats` VARCHAR(16) NULL,
  `nom_empleat` VARCHAR(255) NULL,
  `Ventes_id_venta` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id_empleats`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Proveïdors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Proveïdors` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Proveïdors` (
  `id_proveïdor` VARCHAR(16) NOT NULL,
  `Nom_proveïdor` VARCHAR(45) NULL,
  `adreça` VARCHAR(255) NULL,
  `telfon` VARCHAR(9) NULL,
  `NIF` VARCHAR(7) NULL,
  PRIMARY KEY (`id_proveïdor`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `NIF_UNIQUE` ON `Proveïdors` (`NIF` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ulleres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ulleres` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Ulleres` (
  `id_ulleres` INT NOT NULL,
  `model` VARCHAR(45) NULL,
  `Ullerescol` VARCHAR(45) NULL,
  `Marca` VARCHAR(45) NULL,
  `Graduació` VARCHAR(45) NULL,
  `Color_muntura` VARCHAR(45) NULL,
  `Color_vidre` VARCHAR(45) NULL,
  `Preu` DECIMAL(10) NULL,
  `Proveïdors_id_proveïdor` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id_ulleres`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ventes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ventes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Ventes` (
  `id_venta` VARCHAR(16) NULL,
  `modelo` VARCHAR(255) NULL,
  `cantidad` INT NULL,
  `nom_empleat` VARCHAR(45) NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_venta`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

